1. List (built-in list)
python
Copy
Edit
a = [1, 2, 3, 4]
✅ Built-in Python data type.

✅ Can store different data types: integers, strings, floats, even other lists.

python
Copy
Edit
a = [1, "hello", 3.14, [4, 5]]
✅ Dynamically resizable.

❌ Not memory-efficient for large numeric data.

❌ Slower for numerical operations compared to arrays.

 2. Array (from array module or numpy)
Python has two types of arrays:

🔹 a) array.array (standard library)
python
Copy
Edit
from array import array
a = array('i', [1, 2, 3, 4])  # 'i' stands for integer
✅ More memory-efficient than lists for large numeric data.

❌ Can only store one data type (e.g., all integers or all floats).

✅ Good for numeric tasks, but limited features.

🔹 b) numpy.array (most commonly used)
python
Copy
Edit
import numpy as np
a = np.array([1, 2, 3, 4])
✅ Highly efficient for numerical computations.

✅ Supports vectorized operations (like a + 5 adds 5 to every element).

✅ Can be multi-dimensional (matrices, tensors).

✅ Fast and optimized (used heavily in data science, ML, etc.).

❌ Requires installing the NumPy library.

In [21]:
import numpy as np

In [22]:
!pip install numpy

In [23]:
## 1D array

import numpy as np

arr1=np.array([1,2,3,4,5])   ## here we can give lists or tuples
print(arr1)
print(type(arr1))

arr1=np.array(range(1,6))
print(arr1)
print(type(arr1))
print(arr1.shape)

arr1=np.array([range(1,6)])   ## here it is 2D array
print(arr1)
print(type(arr1))

print(arr1.shape)  ## it means it is 1D and there is only. There is no specific rows and columns

[1 2 3 4 5]
<class 'numpy.ndarray'>
[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
[[1 2 3 4 5]]
<class 'numpy.ndarray'>
(1, 5)


In [24]:
## 2D Array
arr2=np.array([1,2,3,4,5])
a = arr2.reshape(1,5)    ## reshape converts a 1D array to a 2D array and it has 1 row and 5 Columns
print(a)
## Or

arr2=np.array([[1,2,3,4,5]])
b = arr2.shape
print(b)

[[1 2 3 4 5]]
(1, 5)


In [25]:
## 2D array

arr3=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr3)
print(arr3.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [26]:
### Create arrays with inbuild functions

np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [27]:
np.ones((3,4))        ## it helps in deep learning

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
## Identity matrix

a=np.eye(2)
print(a)

b=np.eye(3)
print(b)

[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
## Attributes of Numpy Array

arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])

print("Array:\n",arr)
print("Shape:",arr.shape)
print("Number of Dimention:",arr.ndim)
print("Size:",arr.size)
print("Data Type:",arr.dtype) 
print("Item Size(In Bytes):",arr.itemsize)

Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Shape: (2, 5)
Number of Dimention: 2
Size: 10
Data Type: int64
Item Size(In Bytes): 8


In [30]:
## Numpy Vectorized Operation

arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

##Element wise addition
print("Addition:",arr1+arr2)

##Element wise Substraction
print("Substraction:",arr1-arr2)

##Element wise Multiplication
print("Multiplication:",arr1*arr2)

##Element wise Division
print("Division:",arr1/arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [31]:
## Universal functions (ufuncs): are functions in NumPy that apply operations element-wise on arrays.

arr=np.array([2,3,4,5])

## Square Root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## Natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798]
[  7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.69314718 1.09861229 1.38629436 1.60943791]


In [32]:
## Array slicing and Indexing

arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
print(arr[0][1])

print(arr[0:2,1:])

2
[[2 3]
 [5 6]]


In [34]:
arr[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [35]:
arr[1:,1:]

array([[5, 6],
       [8, 9]])

In [36]:
arr2=np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])

print(arr2)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [37]:
print(arr2[1:,1:3])

[[5 6]
 [8 9]]


In [ ]:
## Modify array elements

arr2[0][0]=100
print(arr2)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [52]:
arr2[1:]=100
print(arr2)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [57]:
## Statistical Problems --> Normalization

## to have a mean of 0 and standard deviation of 1
data=np.array([1,2,3,4,5])

## Calculate the mean and Standard Deviation
mean=np.mean(data)

std_dev=np.std(data)

## Calculate the Normalization
normalization=(data-mean)/std_dev
print(normalization)


[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [58]:
data=np.array([1,2,3,4,5,6,7,8,9,10])

mean=np.mean(data)
print(mean)

median=np.median(data)
print(median)

std_dev=np.array(data)
print(std_dev)

variance=np.var(data)
print(variance)

5.5
5.5
[ 1  2  3  4  5  6  7  8  9 10]
8.25


In [47]:
### Logical operation

arr=np.array(range(1,11))

print(arr>5)
data=arr[arr>5]
print(data)
data2=arr[(arr>=5) & (arr<=8)]
print(data2)


[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[5 6 7 8]
