# Module: NumPy Assignments
## Lesson: NumPy


In [ ]:
### Assignment 1: Array Creation and Manipulation

## 1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

import numpy as np

# arr1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]])

## when we need random data
#arr1=np.random.randint(1,100,size=(5,5))

## when we need fixed data
arr1=np.array([range(1,6),range(5,10),range(9,14),range(13,18),range(16,21)])
print(arr1)
print(arr1.shape)

arr1[0:5,2:3]=1
print(arr1)


## 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

arr2=np.array([range(1,5),range(5,9),range(9,13),range(13,17)])
print(arr2)

np.fill_diagonal(arr2,0)
print(arr2)



[[ 1  2  3  4  5]
 [ 5  6  7  8  9]
 [ 9 10 11 12 13]
 [13 14 15 16 17]
 [16 17 18 19 20]]
(5, 5)
[[ 1  2  1  4  5]
 [ 5  6  1  8  9]
 [ 9 10  1 12 13]
 [13 14  1 16 17]
 [16 17  1 19 20]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [3]:
### Assignment 2: Array Indexing and Slicing

## 1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

arr3=np.arange(1,37).reshape(6,6)
print(arr3)

row_3_to_5=arr3[2:5,1:4]
print(row_3_to_5)

## 2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

arr4=np.random.randint(1,50,size=(5,5))
print(arr4)

top=arr4[0, :]
bottom=arr4[-1,0:]
left=arr4[1:-1,0]
right=arr4[1:-1,-1]
print(top)
print(bottom)
print(right)
print(left)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[14 15 16]
 [20 21 22]
 [26 27 28]]
[[40 35  4 31 19]
 [ 7 20  4 35 25]
 [17  2 34 22  6]
 [11 44 17 17 47]
 [48  7 44 32 10]]
[40 35  4 31 19]
[48  7 44 32 10]
[25  6 47]
[ 7 17 11]


In [4]:
### Assignment 3: Array Operations

## 1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

arr5=np.arange(0,12).reshape(3,4)
arr6=np.arange(12,24).reshape(3,4)
print(arr5)
print(arr6)

# addition
add=arr5+arr6
print(add)

#subtraction
sub=arr5-arr6
print(sub)

#multiplication
mult=arr5*arr6
print(mult)

#division
div=arr5/arr6
print(div)

## 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

arr7=np.arange(0,16).reshape(4,4)
print(arr7)
row_wise=arr7.sum(axis=1)   ## sums across columns for each row.
column_wise=arr7.sum(axis=0)      ## sums across rows for each columns.

print(row_wise)
print(column_wise)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]
[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]
[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 6 22 38 54]
[24 28 32 36]


In [5]:
### Assignment 4: Statistical Operations

## 1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

arr8=np.random.randint(0,24,size=(5,5))
print(arr8)

mean=np.mean(arr8)
print(mean)

median=np.median(arr8)
print(median)

std_dev=np.std(arr8)
print(std_dev)

variance=np.var(arr8)
print(variance)

## 2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

arr9=np.arange(1,10).reshape(3,3)
print(arr9)

normalization=arr8-mean/std_dev
print(normalization)


[[ 0 14 11 15 23]
 [10  9  6 14 10]
 [ 9  0 13  2 14]
 [22  2  3  9 22]
 [21 11  3 22  4]]
10.76
10.0
7.134591789303716
50.9024
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-1.50814515 12.49185485  9.49185485 13.49185485 21.49185485]
 [ 8.49185485  7.49185485  4.49185485 12.49185485  8.49185485]
 [ 7.49185485 -1.50814515 11.49185485  0.49185485 12.49185485]
 [20.49185485  0.49185485  1.49185485  7.49185485 20.49185485]
 [19.49185485  9.49185485  1.49185485 20.49185485  2.49185485]]


In [6]:
### Assignment 5: Broadcasting

## 1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

arr9=np.random.randint(1,11,size=(3,3))

array1D=np.array([3,4,5])

result=arr9+array1D
print(result)

## 2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

arr2D=np.random.randint(0,16,size=(4,4))
print(arr2D)
arr1D=np.array([3,4,5,6])
print(arr1D.reshape(4,1))

subtractArray=arr2D-arr1D.reshape(4,1)
print(subtractArray)



[[12  6 13]
 [ 9  5  8]
 [ 5  8 15]]
[[ 3  9  7 13]
 [14  1  5  4]
 [ 3  9  2 11]
 [13 12  6  9]]
[[3]
 [4]
 [5]
 [6]]
[[ 0  6  4 10]
 [10 -3  1  0]
 [-2  4 -3  6]
 [ 7  6  0  3]]


In [7]:
### Assignment 6: Linear Algebra

## 1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

## matrix=np.arange(0,9).reshape(3,3)   --> If you try computing a determinant with np.arange(0,9) you’ll actually get 0, because the rows are linearly dependent — meaning the matrix is singular and has no inverse.
 
matrix = np.random.randint(1, 10, size=(3, 3))
print(matrix)

determinant=np.linalg.det(matrix)

if determinant!=0:
    inverse=np.linalg.inv(matrix)
    print(f"Matrix:\n",matrix)
else:
    print("Matrix is singular. Inverse doesn't exist here")
eigenvalues=np.linalg.eigvals(matrix)
print(eigenvalues)


## 2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

A=np.random.randint(1,7,size=(2,3))
B=np.random.randint(7,13,size=(3,2))

matrix_mult=np.dot(A,B)
print(matrix_mult)



[[2 7 1]
 [4 3 4]
 [4 4 6]]
Matrix:
 [[2 7 1]
 [4 3 4]
 [4 4 6]]
[11.67566891 -2.39337468  1.71770577]
[[103 101]
 [ 83  82]]


In [8]:
### Assignment 7: Advanced Array Manipulation

## 1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

arr=np.random.randint(1,10,size=(3,3))
print(arr)

arr_shape_1_to_9=arr.reshape(1,9)
print(arr_shape_1_to_9)

arr_shape_9_to_1=arr.reshape(9,1)
print(arr_shape_9_to_1)

## 2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).  (arr.flatten() converts the 2D array into a 1D array )

arr=np.random.randint(1,26,size=(5,5))
print(arr)

flatten=arr.flatten()
print(flatten)

reshape_5_5=flatten.reshape(5,5)
print(reshape_5_5)


[[4 6 4]
 [8 6 5]
 [2 8 1]]
[[4 6 4 8 6 5 2 8 1]]
[[4]
 [6]
 [4]
 [8]
 [6]
 [5]
 [2]
 [8]
 [1]]
[[ 9 11 14  4 21]
 [20 25  1 13 11]
 [24 20 15 19 11]
 [19  8 10 18  4]
 [25 13 21 24  8]]
[ 9 11 14  4 21 20 25  1 13 11 24 20 15 19 11 19  8 10 18  4 25 13 21 24
  8]
[[ 9 11 14  4 21]
 [20 25  1 13 11]
 [24 20 15 19 11]
 [19  8 10 18  4]
 [25 13 21 24  8]]


In [ ]:
### Assignment 8: Fancy Indexing and Boolean Indexing

## 1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

arr=np.random.randint(0,25,size=(5,5))
print(arr)

corners=arr[
        [0,0,4,4],
        [0,4,0,4]
           ]

print(corners)

## 2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

arr2=np.random.randint(0,16,size=(4,4))
print(arr2)
greater_than_10=arr2>10

print(greater_than_10)



[[ 4  9 22  6 19]
 [ 7  5 22 24 20]
 [15 15  4  1  4]
 [23 15 23  2 19]
 [ 8 21 19  3  4]]
[ 4 19  8  4]
[[ 2  1  3  9]
 [13  0  7  0]
 [10 10  1  5]
 [ 5  5  5  5]]
[[False False False False]
 [ True False False False]
 [False False False False]
 [False False False False]]


In [14]:
### Assignment 9: Structured Arrays

## 1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

data_type=[('name','U10'),('age','i4'),('weight','f4')]
data =np.array(
    [
        ('Nuhan', 24, 65.5),
        ('Tousif', 25, 65.8),
        ('Gazi', 22, 67.5)
    ],
    dtype=data_type
)

sorted=np.sort(data,order='age')
print(sorted)

## 2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

data_type2=[('x','i4'),('y','i4')]
points=np.array([
     (4,5),
     (7,8),
     (1,2)
],
dtype=data_type2
)

def euclidean_distance(p1, p2):
    return np.sqrt((p1['x'] - p2['x'])**2 + (p1['y'] - p2['y'])**2)

n = len(points)
distance_matrix = np.zeros((n, n))

for i in range(n):
    for j in range(n):
        distance_matrix[i, j] = euclidean_distance(points[i], points[j])

print("Points:\n", points)
print("\nEuclidean Distance Matrix:\n", distance_matrix)


[('Gazi', 22, 67.5) ('Nuhan', 24, 65.5) ('Tousif', 25, 65.8)]
Points:
 [(4, 5) (7, 8) (1, 2)]

Euclidean Distance Matrix:
 [[0.         4.24264069 4.24264069]
 [4.24264069 0.         8.48528137]
 [4.24264069 8.48528137 0.        ]]


In [6]:
### Assignment 10: Masked Arrays

## 1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

import numpy as np
import numpy.ma as ma

arr=np.random.randint(1,21,size=(4,4))

mask_greater_than_10=ma.masked_greater(arr,10)
print(mask_greater_than_10)

sum_unmasked=mask_greater_than_10.sum()
print(sum_unmasked)

## 2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.
np.random.seed(1)
arr2=np.random.randint(1,21,size=(3,3))
print(arr2)
masked_diagonal=ma.masked_array(arr2,mask=np.eye(3,dtype=bool))

print(masked_diagonal)

unMasked_mean=masked_diagonal.mean()
print(unMasked_mean)

filled_array=masked_diagonal.filled(unMasked_mean)
print(filled_array)



[[-- 2 -- 8]
 [-- 7 -- 6]
 [-- -- -- --]
 [-- 5 10 --]]
38
[[ 6 12 13]
 [ 9 10 12]
 [ 6 16  1]]
[[-- 12 13]
 [9 -- 12]
 [6 16 --]]
11.333333333333334
[[11 12 13]
 [ 9 11 12]
 [ 6 16 11]]
