# Module: NumPy Assignments
## Lesson: NumPy


In [10]:
### Assignment 1: Array Creation and Manipulation

## 1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

import numpy as np

# arr1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]])
arr1=np.array([range(1,6),range(5,10),range(9,14),range(13,18),range(16,21)])
print(arr1)
print(arr1.shape)

arr1[0:5,2:3]=1
print(arr1)


## 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

arr2=np.array([range(1,5),range(5,9),range(9,13),range(13,17)])
print(arr2)

np.fill_diagonal(arr2,0)
print(arr2)



[[ 1  2  3  4  5]
 [ 5  6  7  8  9]
 [ 9 10 11 12 13]
 [13 14 15 16 17]
 [16 17 18 19 20]]
(5, 5)
[[ 1  2  1  4  5]
 [ 5  6  1  8  9]
 [ 9 10  1 12 13]
 [13 14  1 16 17]
 [16 17  1 19 20]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [11]:
### Assignment 2: Array Indexing and Slicing

## 1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

arr3=np.arange(1,37).reshape(6,6)
print(arr3)

row_3_to_5=arr3[2:5,1:4]
print(row_3_to_5)

## 2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

arr4=np.random.randint(1,50,size=(5,5))
print(arr4)

top=arr4[0, :]
bottom=arr4[-1,0:]
left=arr4[1:-1,0]
right=arr4[1:-1,-1]
print(top)
print(bottom)
print(right)
print(left)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[14 15 16]
 [20 21 22]
 [26 27 28]]
[[38 19  1 21  1]
 [ 7 13 22  5 33]
 [34  7 22 15 22]
 [41 49  3 28  8]
 [ 3  8 36 14  5]]
[38 19  1 21  1]
[ 3  8 36 14  5]
[33 22  8]
[ 7 34 41]


In [12]:
### Assignment 3: Array Operations

## 1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

arr5=np.arange(0,12).reshape(3,4)
arr6=np.arange(12,24).reshape(3,4)
print(arr5)
print(arr6)

# addition
add=arr5+arr6
print(add)

#subtraction
sub=arr5-arr6
print(sub)

#multiplication
mult=arr5*arr6
print(mult)

#division
div=arr5/arr6
print(div)

## 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

arr7=np.arange(0,16).reshape(4,4)
print(arr7)
row_wise=arr7.sum(axis=1)   ## sums across columns for each row.
column_wise=arr7.sum(axis=0)      ## sums across rows for each columns.

print(row_wise)
print(column_wise)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]
[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]
[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 6 22 38 54]
[24 28 32 36]


In [19]:
### Assignment 4: Statistical Operations

## 1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

arr8=np.random.randint(0,24,size=(5,5))
print(arr8)

mean=np.mean(arr8)
print(mean)

median=np.median(arr8)
print(median)

std_dev=np.std(arr8)
print(std_dev)

variance=np.var(arr8)
print(variance)

## 2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

arr9=np.arange(1,10).reshape(3,3)
print(arr9)

normalization=arr8-mean/std_dev
print(normalization)


[[ 9 16 13  5 23]
 [ 0 18  6  2  8]
 [12  8 22 22 13]
 [12  3 15 10 12]
 [ 8  9  5  5  3]]
10.36
9.0
6.247431472213201
39.0304
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 7.34171851 14.34171851 11.34171851  3.34171851 21.34171851]
 [-1.65828149 16.34171851  4.34171851  0.34171851  6.34171851]
 [10.34171851  6.34171851 20.34171851 20.34171851 11.34171851]
 [10.34171851  1.34171851 13.34171851  8.34171851 10.34171851]
 [ 6.34171851  7.34171851  3.34171851  3.34171851  1.34171851]]


In [25]:
### Assignment 5: Broadcasting

## 1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

arr9=np.random.randint(1,11,size=(3,3))

array1D=np.array([3,4,5])

result=arr9+array1D
print(result)

## 2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

arr2D=np.random.randint(0,16,size=(4,4))
print(arr2D)
arr1D=np.array([3,4,5,6])
print(arr1D.reshape(4,1))

subtractArray=arr2D-arr1D.reshape(4,1)
print(subtractArray)



[[12  5  6]
 [ 8  5 15]
 [13 14 12]]
[[10  9  3 12]
 [ 1  4  2  3]
 [13 14  4 10]
 [14 11  4  1]]
[[3]
 [4]
 [5]
 [6]]
[[ 7  6  0  9]
 [-3  0 -2 -1]
 [ 8  9 -1  5]
 [ 8  5 -2 -5]]


In [ ]:
### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.


In [ ]:
### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [ ]:
### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [2]:
### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

SyntaxError: invalid syntax (4160199345.py, line 3)

In [ ]:
### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.